=begin
#Wekan REST API

#The REST API allows you to control and extend Wekan with ease.  If you are an end-user and not a dev or a tester, [create an issue](https://github.com/wekan/wekan/issues/new) to request new APIs.  > All API calls in the documentation are made using `curl`.  However, you are free to use Java / Python / PHP / Golang / Ruby / Swift / Objective-C / Rust / Scala / C# or any other programming languages.  # Production Security Concerns When calling a production Wekan server, ensure it is running via HTTPS and has a valid SSL Certificate. The login method requires you to post your username and password in plaintext, which is why we highly suggest only calling the REST login api over HTTPS. Also, few things to note:  * Only call via HTTPS * Implement a timed authorization token expiration strategy * Ensure the calling user only has permissions for what they are calling and no more 

OpenAPI spec version: v4.17

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15-SNAPSHOT

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/boards'
require 'swagger_client/models/boards_labels'
require 'swagger_client/models/boards_members'
require 'swagger_client/models/card_comments'
require 'swagger_client/models/cards'
require 'swagger_client/models/cards_customfields'
require 'swagger_client/models/cards_vote'
require 'swagger_client/models/checklist_items'
require 'swagger_client/models/checklists'
require 'swagger_client/models/custom_fields'
require 'swagger_client/models/custom_fields_settings'
require 'swagger_client/models/custom_fields_settings_dropdownitems'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_3_items'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/integrations'
require 'swagger_client/models/lists'
require 'swagger_client/models/lists_wiplimit'
require 'swagger_client/models/swimlanes'
require 'swagger_client/models/users'
require 'swagger_client/models/users_emails'
require 'swagger_client/models/users_profile'

# APIs
require 'swagger_client/api/boards_api'
require 'swagger_client/api/card_comments_api'
require 'swagger_client/api/cards_api'
require 'swagger_client/api/checklist_items_api'
require 'swagger_client/api/checklists_api'
require 'swagger_client/api/custom_fields_api'
require 'swagger_client/api/integrations_api'
require 'swagger_client/api/lists_api'
require 'swagger_client/api/login_api'
require 'swagger_client/api/swimlanes_api'
require 'swagger_client/api/users_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
